[package]
name = "htmlpacker"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
maud = "*"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.28", features = ["full"] }
url = "2.5.4"
