# this is an example config
pack:
  # this option enables the core runtime environment that i have built
  # core.js and wasm_decoder for brotli decode of wasm_modules
  runtime:
    enabled: true
  meta:
    title: "htmlpacker"
    author: "me"
    description: "packed by htmlpacker"
    keywords: "hello from yaml"
  #favicon:
    #local: 
    #  - "./core/icon.svg"
    #remote:
  #css:
    #local:
    #remote:
    #  - "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
  scripts:
    local:
      #- "../wasm_decoder/pkg/wasm_decoder.js"
      - "../wasm_modules/pkg/wasm_modules.js"
      # - "./core/core.js"  
    #remote:
    #  - "https://cdn.jsdelivr.net/npm/three@0.132.2/build/three.min.js"
    #  - "https://cdn.jsdelivr.net/npm/three@0.132.2/examples/js/controls/TrackballControls.min.js"
  wasm:
    # decoder should be default?
    #decoder:
    #  compile_wasm: false
    #  path: "../wasm_decoder/pkg/wasm_decoder_bg.wasm"
    #  id: "bin-wasm-decoder"
    #  compression: "none"
    module:
      compile_wasm: false
      path: "../wasm_modules/pkg/wasm_modules_bg.wasm"
      # currently this module needs to be called bin-wasm-app
      # for the core.js to load it properly
      id: "bin-wasm-app"
      compression: "brotli"

