pack:
  meta:
    title: "htmlpacker"
    author: "me"
    description: "packed by htmlpacker"
    keywords: "hello from yaml"
  favicon:
    local: 
      - "./core/icon.svg"
    #remote:
  css:
    #local:
    remote:
      - "https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
  scripts:
    local:
      - "../wasm_decoder/pkg/wasm_decoder.js"
      - "../wasm_modules/pkg/wasm_modules.js"
      - "./core/core.js"  
    #remote:
    #  - "https://cdn.jsdelivr.net/npm/three@0.132.2/build/three.min.js"
    #  - "https://cdn.jsdelivr.net/npm/three@0.132.2/examples/js/controls/TrackballControls.min.js"
  wasm:
    # decoder should be default?
    decoder:
      compile_wasm: true
      path: "../wasm_decoder/pkg/wasm_decoder_bg.wasm"
      id: "bin-wasm-decoder"
      compression: "none"
    module:
      compile_wasm: true
      path: "../wasm_modules/pkg/wasm_modules_bg.wasm"
      id: "bin-wasm-app"
      compression: "brotli"

